-- MySQL Script generated by MySQL Workbench
-- Wed May 10 17:17:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Data for table `taxReports`.`role_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`role_list` (`code`, `name`) VALUES ('#1', 'Admin');
INSERT INTO `taxReports`.`role_list` (`code`, `name`) VALUES ('#2', 'Customer');
INSERT INTO `taxReports`.`role_list` (`code`, `name`) VALUES ('#3', 'Inspector');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`residency_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`residency_list` (`code`, `name`) VALUES ('#1', 'Resident');
INSERT INTO `taxReports`.`residency_list` (`code`, `name`) VALUES ('#2', 'Non-resident');
INSERT INTO `taxReports`.`residency_list` (`code`, `name`) VALUES ('#3', 'Undefined');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`person_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`person_list` (`code`, `name`) VALUES ('#1', 'Individual');
INSERT INTO `taxReports`.`person_list` (`code`, `name`) VALUES ('#2', 'Legal entity');
INSERT INTO `taxReports`.`person_list` (`code`, `name`) VALUES ('#3', 'Undefined');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`status_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`status_list` (`code`, `name`, `closed`) VALUES ('#1', 'Supplied', 0);
INSERT INTO `taxReports`.`status_list` (`code`, `name`, `closed`) VALUES ('#2', 'Accepted', 1);
INSERT INTO `taxReports`.`status_list` (`code`, `name`, `closed`) VALUES ('#3', 'Returned', 0);
INSERT INTO `taxReports`.`status_list` (`code`, `name`, `closed`) VALUES ('#4', 'Corrected', 0);
INSERT INTO `taxReports`.`status_list` (`code`, `name`, `closed`) VALUES ('#5', 'Rejected', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`next_statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (1, 2);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (1, 3);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (1, 5);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (3, 4);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (4, 2);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (4, 3);
INSERT INTO `taxReports`.`next_statuses` (`status_id`, `next_status_id`) VALUES (4, 5);

COMMIT;

