-- MySQL Script generated by MySQL Workbench
-- Thu May 11 21:34:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Data for table `taxReports`.`role_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`role_list` (`id`, `code`, `name`) VALUES (1, '#1', 'Customer');
INSERT INTO `taxReports`.`role_list` (`id`, `code`, `name`) VALUES (2, '#2', 'Inspector');
INSERT INTO `taxReports`.`role_list` (`id`, `code`, `name`) VALUES (3, '#3', 'Admin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`residency_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`residency_list` (`id`, `code`, `name`) VALUES (1, '#1', 'Resident');
INSERT INTO `taxReports`.`residency_list` (`id`, `code`, `name`) VALUES (2, '#2', 'Non-resident');
INSERT INTO `taxReports`.`residency_list` (`id`, `code`, `name`) VALUES (3, '#3', 'Undefined');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`person_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`person_list` (`id`, `code`, `name`) VALUES (1, '#1', 'Individual');
INSERT INTO `taxReports`.`person_list` (`id`, `code`, `name`) VALUES (2, '#2', 'Legal entity');
INSERT INTO `taxReports`.`person_list` (`id`, `code`, `name`) VALUES (3, '#3', 'Undefined');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`user_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`user_list` (`id`, `login`, `password`, `first_name`, `last_name`, `mail`, `role_id`, `residency_id`, `person_id`, `is_enable`, `created`, `modified`) VALUES (1, 'Admin', 'Admin', 'admin', 'admin', 'admin@taxReports.org', 3, 3, 3, 0, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`status_list`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`status_list` (`id`, `code`, `name`, `closed`) VALUES (1, '#1', 'Supplied', 0);
INSERT INTO `taxReports`.`status_list` (`id`, `code`, `name`, `closed`) VALUES (2, '#2', 'Accepted', 1);
INSERT INTO `taxReports`.`status_list` (`id`, `code`, `name`, `closed`) VALUES (3, '#3', 'Returned', 0);
INSERT INTO `taxReports`.`status_list` (`id`, `code`, `name`, `closed`) VALUES (4, '#4', 'Corrected', 0);
INSERT INTO `taxReports`.`status_list` (`id`, `code`, `name`, `closed`) VALUES (5, '#5', 'Rejected', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `taxReports`.`next_statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxReports`;
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (1, 1, 2);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (2, 1, 3);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (3, 1, 5);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (4, 3, 4);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (5, 4, 2);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (6, 4, 3);
INSERT INTO `taxReports`.`next_statuses` (`id`, `status_id`, `next_status_id`) VALUES (7, 4, 5);

COMMIT;

